import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/main-layout";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`times-new-roman ${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <NextTopLoader 
          color="#1C46F5" 
          height={2} 
          showSpinner={false} 
        />
        <MainLayout>
        {children}
        </MainLayout>
      </body>
    </html>
  );
}
